server:
  port: 0

spring:
  application:
    name: CATALOG-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/learncode_db_fn
    username: postgres
    password: sql
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: catalog_schema
        format_sql: true

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

cloudinary:
  cloud-name: dq3ut13kr
  api-key: "449415717531214"
  api-secret: "_7AoYNN1ufdyI2KYE8jhZ85K67w"