server:
  port: 0

spring:
  application:
    name: SUBSCRIPTION-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/learncode_db
    username: postgres
    password: sql
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: subscription_schema
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          audiences: "107744191965-81u4lmkf2s6r93vjbf5s0nji42h0sa5d.apps.googleusercontent.com"

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

stripe:
  secret:
    key: "sk_test_51Sy10wHzcCFteY6Pbsece0dYpgZ2eSjsddjqZF5dUNhYQp8h1l6qP4ibHs7lSmAfKtkHSOkelPuGuNtTdyRv2Nox0066MYi8hg"

  webhook:
    secret: "whsec_3620bd911db45c716a5f06d90121d70d62aae93d1d685e365489e6d134320af8"